---
- name: Patch Linux hosts
  hosts: all
  
  tasks:
 
  - name: Upgrade all packages on CentOS/RHEL hosts
    yum:
      name: '*'
      state: latest
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: Upgrade all packages on Ubuntu/Debian hosts
    apt:
      upgrade: dist
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

  - name: Upgrade all packages on Fedora hosts
    dnf:
      name: '*'
      state: latest
    when: ansible_distribution == 'Fedora'
 
  - name: Upgrade all packages on OpenSUSE hosts
    zypper:
      name: '*'
      state: latest
    when: ansible_distribution == "{{'OpenSUSE' in ansible_distribution}}"
